version: "3.9"

services:
  test-service:
     build:
       context: .
       dockerfile: TestProject/Dockerfile
       
  counter-service:
    build:
      context: .
      dockerfile: DivisorCounter/Dockerfile
  cache-service:
    build:
      context: .
      dockerfile: CacheService/Dockerfile
    depends_on:
      - cache-db
    ports:
      - "5007:80"
  cache-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "cache-database"
      MYSQL_USER: "div-cache"
      MYSQL_PASSWORD: "C@ch3d1v"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"